services:
  # --------------------
  # Monitoring stack
  # --------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "6060:6060"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "8080:8080"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  # --------------------
  # SonarQube
  # --------------------
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped

  # --------------------
  # Nexus
  # --------------------
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
      - "8083:8083"
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

# --------------------
# Volumes
# --------------------
volumes:
  grafana-data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  nexus-data:
