---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  type: NodePort
  selector:
    app: node-exporter
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30900
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
    - name: nexus-http    # 👈 service port name
      port: 8081          # 👈 service port
      targetPort: 8081    # 👈 forwards to containerPort
      nodePort: 30881     # 👈 externally accessible
    - name: nexus-repo
      port: 8083
      targetPort: 8083
      nodePort: 30883

